export const  ContributorData = [
    {
      id: 1,
      name: "Vishnu Goswami",
      img: "https://live.staticflickr.com/65535/54037306066_16ba1b8cd7_z.jpg",
      role: "Web Dev",
      social1: "https://github.com/WebVishnu",
      social2: "https://www.linkedin.com/in/vishnu-goswami",
      desc: "Funniest guy in the room (that's what he said)",
    },
    {
      id: 2,
      name: "Prince Sharma",
      img: "https://live.staticflickr.com/65535/54037648148_973171e255_z.jpg",
      role: "Web Dev",
      social1: "http://www.linkedin.com/in/prince-sharma-047973253",
      social2: "https://github.com/Prince-Sharma002/",
      desc: "Funniest guy in the room (that's what he said)",
    },
    {
      id: 2,
      name: "Nikita Kumari Singh",
      img: "https://live.staticflickr.com/65535/54037852058_2755e63182_z.jpg",
      role: "Lead",
      social1: "https://www.linkedin.com/in/nikita-kumari-58455b284/",
      social2: "https://github.com/Nikitakumarisingh",
      desc: "Leader for a reason",
    },
    {
      id: 2,
      name: "Smrita Shukla",
      img: "https://live.staticflickr.com/65535/54041766082_770e8577a5_z.jpg",
      role: "UI Design",
      social1: "https://www.linkedin.com/in/smrita-shukla-7bb420243/",
      social2: "https://github.com/smritashukla",
      desc: "",
    },
    {
      id: 2,
      name: "Utkarsh Aggarwal",
      img: "https://live.staticflickr.com/65535/54036432067_84faf80a02_z.jpg",
      role: "CyberSecurity",
      social1: "https://www.linkedin.com/in/utkarshcse26",
      social2: "https://github.com/utkarshcse2026",
      desc: "QA testing",
    },
    {
      id: 2,
      name: "Smita Tripathi",
      img: "https://live.staticflickr.com/65535/54037919555_d0b96721d5_z.jpg",
      role: "Design",
      social1: "http://www.linkedin.com/in/smita-tripathi-a23570251",
      social2: "https://github.com/smitatripathi417",
      desc: "",
    },
      {
        id: 2,
        name: "Ishaan",
        img: "https://avatars.githubusercontent.com/u/113186458?v=4",
        role: "Open Source",
        social1: "https://x.com/Ishaan2053",
        social2: "https://github.com/Ishaan2053",
        desc: "Secretive even when all he has to hide is a 10 ki chocolate",
      },
      {
        id: 3,
        name: "Pranav Tripathi",
        img: "https://github.com/prnvtripathi.png",
        role: "Web Developer",
        social1: "https://x.com/prnvtwts",
        social2: "https://github.com/prnvtripathi",
        desc: "The guy who's always in a hurry",
      },
      {
        id: 2102901550041,
        name: "Vansh Goel",
        img: "https://github.com/vanshgoel18.png",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/vansh-goel-100928221/",
        social2: "https://x.com/GoelVansh_19",
        desc: " ",
      },
      {
        id: 5,
        name: "Kabir",
        img: "https://avatars.githubusercontent.com/u/147363110?v=4",
        role: "App Development Contributor",
        social1: "https://x.com/KabirShukl",
        social2: "https://www.linkedin.com/in/kabir-shukla-396247233/",
        desc: "Aspiring Jim Halpert",
      },
      {
        id: 2002900100107,
        name: "Prakhar Sharma",
        img: "https://zippy-starburst-d78231.netlify.app/assets/heroImage-C3swbDr5.jpg",
        role: "contributer",
        social1: "www.linkedin.com/in/prakhar-sharma-96a831272",
        social2: "",
        desc: "Java developer,learner",
      },
      {
        id: 2102900100080,
        name: "Manish Keshwani",
        img: "https://avatars.githubusercontent.com/u/113196913?v=4",
        role: "Web Developer",
        social1: "https://x.com/keshwani2002",
        social2: "https://www.linkedin.com/in/manish-kumar-keshwani-052b61243/",
        desc: "Once a nerd, always a nerd.",
      },
      {
        id: 197,
        name: "RaviShankar Yadav",
        img: "https://i.ibb.co/cDjR7K3/IMG-20241223-101731740-HDR-AE.jpg",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/ravi-yadav-64305b265?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        social2: "",
        desc: "Testing things",
      },
      {
        id: 198,
        name: "Ritik Kumar Parvat",
        img: "https://i.ibb.co/Cz57CRm/IMG-20241226-WA0002.jpg",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/ritik-kumar-parvat-a53759253?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        social2: "https://github.com/RitikKumarParvat",
        desc: "Testing Website",
      },
      {
        id: 198,
        name: "Prince Srivastava",
        img: "https://i.ibb.co/Ybw1JnY/Snapchat-1385600909.jpg",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/prince-srivastava-960461274?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        social2: "https://github.com/mcuthor",
        desc: "Testing Website",
      },


      {
        id: 2202901540039,
        name: "Ashiya Rana",
        img: "https://github.com/Ashiyarana12.png",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/ashiya-rana-8ba667251/",
        social2: "https://github.com/Ashiyarana12",
        desc: "just testing ",
      },
      {
        id: 2202900100138,
        name: "Pratyush Mathur",
        img: "https://github.com/Shoto0095.png",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/pratyush-mathur-35a1a2251/",
        social2: "https://github.com/Shoto0095",
        desc: "Just testing things ;) ",
      },
      {
        id: 2202900100165,
        name: "Shirshak Kumar",
        img: "https://github.com/shirshakk.png",
        role: "App Development Contributor",
        social1: "https://x.com/kshirshak76",
        social2: "https://www.linkedin.com/in/shirshak-kumar-5ba790253",
        desc: "Aspiring Jim Halpert",
      },
      {
        id: "2202900100070",
        name: "Daksh Agarwal",
        img: "https://avatars.githubusercontent.com/u/133400136?v=4",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/dakshagarwal5/",
        social2: "https://x.com/Dakshagarwal_5",
        desc: "",
      },
      {
        id: 2202900100091,
        name: "Himanshi Rana",
        img: "https://avatars.githubusercontent.com/u/139847752?v=4",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/himanshi-rana-b4b9b9251/",
        social2: "https://github.com/himanshirana2403",
        desc: "",
      },
      {
        id: 2202901520127,
        name: "Pulkit Gahlot",
        img: "https://avatars.githubusercontent.com/u/87379387?s=400&u=5ed5f79d454863f8b3c2a44a6417709d250800c4&v=4",
        role: "Contributor",
        social1: "https://www.linkedin.com/in/pulkit-gahlot-399187251/",
        social2: "https://x.com/Pulkit_1527",
        desc: "Maybe/Maybe not :p",
      },
      {
        id: 2102901550042,
        name: "Vishal kumar Pandey",
        img: "https://github.com/VishaaLPandey.png",
        role: "Contributor",
        social1: "https://x.com/pandeytwt?t=UlEC380rSrTVri0IM6otLw&s=09",
        social2: "https://github.com/VishaaLPandey",
        desc: "A Curious guy who is everywhere in Tech and Sports.",
      },
      {
        id: 2202900100147,
        name: "Rishikesh Gupta",
        img: "https://avatars.githubusercontent.com/u/112187328?v=4",
        role: "Contributor",
        social1: "https://www.instagram.com/pranjalll_x_beyonder/",
        social2: "https://www.youtube.com/@beyonder001",
        desc: "yup buddy!! all good ?",
      },
      {
        id: "22029",
        name: "Amit Verma",
        img: "https://github.com/amitverma147.png",
        role: "Developer",
        social1: "https://x.com/Amit_v6",
        social2: "https://www.instagram.com/amitv.147/",
        desc: "Memes Lover!!",
      },
      {
        id: 2102901540039,
        name: "chirag sharma",
        img: "https://pbs.twimg.com/profile_images/1736850249585770496/lqltdrxl_400x400.jpg",
        role: "open source contributor",
        social1: "https://x.com/itschirag24",
        social2: "https://github.com/24chirag",
        desc: "Frontend  developer as well as Machine learning enthusiast",
      },
      {
        id: 2202900100071,
        name: "Darshil Kumar",
        img: "https://avatars.githubusercontent.com/u/91634586?v=4",
        role: "Contributor",
        social1: "https://x.com/Darshil88505969",
        social2: "https://www.linkedin.com/in/not-darshil-kumar/",
        desc: "Life is too short for bad vibes.",
      },
      {
        id: 2202900100009,
        name: "Abhinav Gupta",
        img: "https://avatars.githubusercontent.com/u/132747736?v=4",
        role: "Contributor",
        social1: "https://linktr.ee/abhinav_cse",
        social2: "https://www.linkedin.com/in/abhinav-gupta-cs/",
        desc: "You are the CSS to my HTML",
      },
      {
        id: 2202901550044,
        name: "Maanvi Tyagi",
        img: "https://avatars.githubusercontent.com/u/123249667?v=4",
        role: "Contributer",
        social1: "https://github.com/Maanvi025",
        social2:
          "https://www.linkedin.com/in/maanvi-tyagi-70374224b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app ",
        desc: "inquisitive worm",
      },
      {
        id: 2202900100115,
        name: "Mayank Kumar",
        img: "https://avatars.githubusercontent.com/u/126708321?v=4",
        role: "Contributor",
        social1: "https://x.com/mayk7983?t=FttankGMJoph69oxY6QPbw&s=09",
        social2: "https://www.linkedin.com/in/mayank-kumar-773602251",
      },
      {
        id: 6,
        name: "Harshit",
        img: "https://avatars.githubusercontent.com/u/110588667?v=4.png",
        role: "Contributor",
        social1: "https://x.com/Harshit_0553",
        social2: "https://www.linkedin.com/in/harshit-keshari-932435239/",
        desc: "Aspiring Jim Halpert",
      },
  
      {
        id: 2202900100003,
        name: "Aayush Chauhan",
        img: "https://github.com/aayush-506.png",
        role: "Web  Development Contributor",
        social1: "https://x.com/aayush_506?t=1J7JPDuky9Utt2PwYifX-A&s=08",
        social2: "https://www.linkedin.com/in/aayush-chauhan-94556b246",
        desc: "web3 learner ",
      },
      {
        id: 511729,
        name: "Prateek Sinha",
        img: "https://avatars.githubusercontent.com/u/111572443?v=4.png",
        role: "Contributor",
        social1: "https://x.com/hey_Patrickk?t=vKBQfObKBUzcFcPPHvOf0w&s=03",
        social2: "www.linkedin.com/in/prateeksinha5100",
        desc: "Learner",
      },
      //
      {
        id: 42069,
        name: "Aditya Srivastava",
        img: "https://github.com/IronicDeGawd.png",
        role: "App Dev Team",
        social1: "https://x.com/irony_aditya",
        social2: "https://www.linkedin.com/in/aditya-srivastava-bb5008251/",
        desc: "Nerdy ash, tinkering around",
      },
      {
        id: 2202900100004,
        name: "Aayush chauhan",
        img: "https://avatars.githubusercontent.com/u/140552699?s=400&u=e009cde3231a7f19cbc7b009ece9bc9913139e56&v=4",
        role: "Contributor",
        social1:
          "https://www.linkedin.com/in/aayush-chauhan-9b8182238?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        social2: "",
        desc: "web developer",
      },
]